development:
  adapter: postgresql
  encoding: unicode
  database: massage-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: massage-test
  pool: 5
  port: 5432
  host: localhost